---
title: "MLE bootstrap diff N"
author: "Margarita Orlova"
date: "December 19, 2019"
output: html_document
---

```{r, echo=FALSE}
library(reticulate)
library(plotrix)
library(vioplot)
source_python("C:/Users/Moonkin/Documents/GitHub/Thesis_single_RNA/analysis/MLE.py")
```

```{r}
bootstrap<-function(boot_number,k_on,k_off,kr,n_cells){
  est=matrix(, nrow = boot_number, ncol = 3)
  x=generate_data(k_on,k_off,kr,n_cells)
  for (i in 1:boot_number){
    boot_x = as.matrix(x[sample(nrow(x),nrow(x),replace=TRUE)])
    est[i,]=MaximumLikelihood(boot_x)}
  return(est)}

MLE_func<-function(boot_number,k_on,k_off,kr,n_cells){
  MLE<-list()
  for (i in 1:length(n_cells)){
    est<-bootstrap(boot_number,k_on,k_off,kr,as.integer(n_cells[i]))
    MLE[[i]] <- est}
  return(MLE)}
```


## I) Small $k_{on}$ and $k_{off}$ case:

```{r}
#True k_on=k_off=0.1
boot_number=500
k_on=as.numeric(0.1)
k_off=as.numeric(0.1)
kr=as.numeric(100)
n_cells<-c(100,200,500,1000)
MLE<-MLE_func(boot_number,k_on,k_off,kr,n_cells)
x1 <- MLE[[1]]
x2 <- MLE[[2]]
x3 <- MLE[[3]]
x4 <- MLE[[4]]
boxplot(log(x1[,1]),log(x2[,1]),log(x3[,1]),log(x4[,1]),xlab="Number of cells",names=c("100", "200","500", "1000"),main="k_on MLE bootstrap")
abline(h = log(0.1),col="red")
boxplot(log(x1[,2]),log(x2[,2]),log(x3[,2]),log(x4[,2]),xlab="Number of cells",names=c("100", "200","500", "1000"),main="k_off MLE bootstrap")
abline(h = log(0.1),col="red")
boxplot(log(x1[,3]),log(x2[,3]),log(x3[,3]),log(x4[,3]),xlab="Number of cells",names=c("100", "200","500", "1000"),main="k_r MLE bootstrap")
abline(h = log(100),col="red")
```


## II) Large $k_{on}$ and $k_{off}$ case: 

```{r}
#True k_on=k_off=10
k_on=as.numeric(10)
k_off=as.numeric(10)
kr=as.numeric(100)
MLE<-MLE_func(boot_number,k_on,k_off,kr,n_cells)
x1 <- MLE[[1]]
x2 <- MLE[[2]]
x3 <- MLE[[3]]
x4 <- MLE[[4]]
boxplot(log(x1[,1]),log(x2[,1]),log(x3[,1]),log(x4[,1]),xlab="Number of cells",names=c("100", "200","500", "1000"),main="k_on MLE bootstrap")
abline(h = log(10),col="red")
boxplot(log(x1[,2]),log(x2[,2]),log(x3[,2]),log(x4[,2]),xlab="Number of cells",names=c("100", "200","500", "1000"),main="k_off MLE bootstrap")
abline(h = log(10),col="red")
boxplot(log(x1[,3]),log(x2[,3]),log(x3[,3]),log(x4[,3]),xlab="Number of cells",names=c("100", "200","500", "1000"),main="k_r MLE bootstrap")
abline(h = log(100),col="red")
```



## III) Large value if $k_{off}$ and small $k_{on}$ case:

```{r, echo=FALSE}
#True k_on=1, k_off=10
k_on=as.numeric(1)
k_off=as.numeric(10)
kr=as.numeric(100)
MLE<-MLE_func(boot_number,k_on,k_off,kr,n_cells)
x1 <- MLE[[1]]
x2 <- MLE[[2]]
x3 <- MLE[[3]]
x4 <- MLE[[4]]
boxplot(log(x1[,1]),log(x2[,1]),log(x3[,1]),log(x4[,1]),xlab="Number of cells",names=c("100", "200","500", "1000"),main="k_on MLE bootstrap")
abline(h = log(1),col="red")
boxplot(log(x1[,2]),log(x2[,2]),log(x3[,2]),log(x4[,2]),xlab="Number of cells",names=c("100", "200","500", "1000"),main="k_off MLE bootstrap")
abline(h = log(10),col="red")
boxplot(log(x1[,3]),log(x2[,3]),log(x3[,3]),log(x4[,3]),xlab="Number of cells",names=c("100", "200","500", "1000"),main="k_r MLE bootstrap")
abline(h = log(100),col="red")
```



## IV) Small value if $k_{off}$ and big $k_{on}$

```{r, echo=FALSE}
#True k_on=10, k_off=1
n_estimates=100
k_on=as.numeric(10)
k_off=as.numeric(1)
kr=as.numeric(100)
MLE<-MLE_func(boot_number,k_on,k_off,kr,n_cells)
x1 <- MLE[[1]]
x2 <- MLE[[2]]
x3 <- MLE[[3]]
x4 <- MLE[[4]]
boxplot(log(x1[,1]),log(x2[,1]),log(x3[,1]),log(x4[,1]),xlab="Number of cells",names=c("100", "200","500", "1000"),main="k_on MLE bootstrap")
abline(h = log(10),col="red")
boxplot(log(x1[,2]),log(x2[,2]),log(x3[,2]),log(x4[,2]),xlab="Number of cells",names=c("100", "200","500", "1000"),main="k_off MLE bootstrap")
abline(h = log(1),col="red")
boxplot(log(x1[,3]),log(x2[,3]),log(x3[,3]),log(x4[,3]),xlab="Number of cells",names=c("100", "200","500", "1000"),main="k_r MLE bootstrap")
abline(h = log(100),col="red")
```






