---
title: "MLE_bootstrap"
author: "Margarita Orlova"
date: "December 4, 2019"
output: html_document
---


```{r, echo=FALSE}
library(reticulate)
library(plotrix)
library(robustbase)
source_python("C:/Users/Moonkin/Documents/GitHub/Thesis_single_RNA/analysis/MLE.py")
```


Bootstrap procedure:

1) Generate 500 cells with given $k_{on}$, $k_{off}$ and $k_r$ parameters

2) For 500 iterations, sample with replacement bootstrapped data

3) Estimate parameters by maximum likelihood

```{r}
bootstrap<-function(boot_number,k_on,k_off,kr,n_cells){
  est=matrix(, nrow = boot_number, ncol = 3)
  x=generate_data(k_on,k_off,kr,n_cells)
  for (i in 1:boot_number){
    boot_x = as.matrix(x[sample(nrow(x),nrow(x),replace=TRUE)])
    est[i,]=MaximumLikelihood(boot_x)}
  return(est)}
```

## I) Small $k_{on}$ and $k_{off}$ case:

```{r}
#True k_on=k_off=0.1
boot_number=500
k_on=as.numeric(0.1)
k_off=as.numeric(0.1)
kr=as.numeric(100)
n_cells=as.integer(500)
est<-bootstrap(boot_number,k_on,k_off,kr,n_cells)

hist(log(est[,1]),breaks=30, main="MLE estimate of k_on parameter,true k_on=0.1")
abline(v=log(0.1),col='red')
paste("true k_on is 0.1;","k_on mean;",round(mean(est[,1],na.rm=TRUE),3),"k_on median", round(median(est[,1],na.rm=TRUE),3),"k_on st.deviation",round(sqrt(var(est[,1])),3))

hist(log(est[,2]),breaks=30, main="MLE estimate of k_off parameter, true k_off=0.1")
abline(v=log(0.1),col='red')
paste("true k_off is 0.1;","k_off mean;",round(mean(est[,2],na.rm=TRUE),3),"k_off median", round(median(est[,2],na.rm=TRUE),3),"k_off st.deviation",round(sqrt(var(est[,2])),3))

hist(log(est[,3]),breaks=30, main="MLE estimate of k_r parameter,true k_r=100")
abline(v=log(100),col='red')
paste("true k_r is 100;","k_r mean;",round(mean(est[,3],na.rm=TRUE),3),"k_r median", round(median(est[,3],na.rm=TRUE),3),"k_r st.deviation",round(sqrt(var(est[,3])),3))
```



## II) Large $k_{on}$ and $k_{off}$ case: 

```{r, echo=FALSE}
#True k_on=k_off=10
k_on=as.numeric(10)
k_off=as.numeric(10)
kr=as.numeric(100)
est<-bootstrap(boot_number,k_on,k_off,kr,n_cells)

hist(log(est[,1]),breaks=30, main="MLE estimate of k_on parameter, true k_on=10")
abline(v=log(10),col='red')
paste("true k_on is 10;","k_on mean;",round(mean(est[,1],na.rm=TRUE),3),"k_on median", round(median(est[,1],na.rm=TRUE),3),"k_on st.deviation",round(sqrt(var(est[,1])),3))

hist(log(est[,2]),breaks=30, main="MLE estimate of k_off parameter, true k_off=10")
abline(v=log(10),col='red')
paste("true k_off is 10;","k_off mean;",round(mean(est[,2],na.rm=TRUE),3),"k_off median", round(median(est[,2],na.rm=TRUE),3),"k_off st.deviation",round(sqrt(var(est[,2])),3))

hist(log(est[,3]),breaks=30, main="MLE estimate of k_r parameter, true k_r=100")
abline(v=log(100),col='red')
paste("true k_r is 100;","k_r mean;",round(mean(est[,3],na.rm=TRUE),3),"k_r median", round(median(est[,3],na.rm=TRUE),3),"k_r st.deviation",round(sqrt(var(est[,3])),3))
```



## III) Large value if $k_{off}$ and small $k_{on}$ case:


```{r, echo=FALSE}
#True k_on=1, k_off=10
k_on=as.numeric(1)
k_off=as.numeric(10)
kr=as.numeric(100)
est<-bootstrap(boot_number,k_on,k_off,kr,n_cells)


hist(log(est[,1]),breaks=30, main="MLE estimate of k_on parameter, true k_on=1")
abline(v=log(1),col='red')
paste("true k_on is 1;","k_on mean;",round(mean(est[,1],na.rm=TRUE),3),"k_on median", round(median(est[,1],na.rm=TRUE),3),"k_on st.deviation",round(sqrt(var(est[,1])),3))

hist(log(est[,2]),breaks=30, main="MLE estimate of k_off parameter, true k_off=10")
abline(v=log(10),col='red')
paste("true k_off is 10;","k_off mean;",round(mean(est[,2],na.rm=TRUE),3),"k_off median", round(median(est[,2],na.rm=TRUE),3),"k_off st.deviation",round(sqrt(var(est[,2])),3))

hist(log(est[,3]),breaks=30, main="MLE estimate of k_r parameter, true k_r=100")
abline(v=log(100),col='red')
paste("true k_r is 100;","k_r mean;",round(mean(est[,3],na.rm=TRUE),3),"k_r median", round(median(est[,3],na.rm=TRUE),3),"k_r st.deviation",round(sqrt(var(est[,3])),3))
```


## IV) Small value if $k_{off}$ and big $k_{on}$


```{r,echo=FALSE}
#True k_on=10, k_off=1
k_on=as.numeric(10)
k_off=as.numeric(1)
kr=as.numeric(100)
est<-bootstrap(boot_number,k_on,k_off,kr,n_cells)

hist(log(est[,1]),breaks=30, main="MLE estimate of k_on parameter,1000 runs, true k_on=10")
abline(v=log(10),col='red')
paste("true k_on is 10;","k_on mean;",round(mean(est[,1],na.rm=TRUE),3),"k_on median", round(median(est[,1],na.rm=TRUE),3),"k_on st.deviation",round(sqrt(var(est[,1])),3))

hist(log(est[,2]),breaks=30, main="MLE estimate of k_off parameter,1000 runs, true k_off=1")
abline(v=log(1),col='red')
paste("true k_off is 1;","k_off mean;",round(mean(est[,2],na.rm=TRUE),3),"k_off median", round(median(est[,2],na.rm=TRUE),3),"k_off st.deviation",round(sqrt(var(est[,2])),3))

hist(log(est[,3]),breaks=30, main="MLE estimate of k_r parameter,1000 runs, true k_r=100")
abline(v=log(100),col='red')
paste("true k_r is 100;","k_r mean;",round(mean(est[,3],na.rm=TRUE),3),"k_r median", round(median(est[,3],na.rm=TRUE),3),"k_r st.deviation",round(sqrt(var(est[,3])),3))
```

