---
title: "Question_1"
author: "Margarita Orlova"
date: "February 8, 2020"
output:
  word_document: default
  html_document: default
---

```{r}
library(reticulate)
library(robustbase)
source_python("C:/Users/Moonkin/Documents/GitHub/Thesis_single_RNA/analysis/MLE.py")
clean_data<-read.table("C:/Users/Moonkin/Documents/GitHub/Thesis_single_RNA/analysis/clean_dataset_for_analysis.txt", header = T, sep = "\t")
```

```{r}
estimate_MLE_one_gene<-function(full_data){
  data_ind<-substr(colnames(full_data),0,7)
  data_ind<-data_ind[2:length(data_ind)]
  est=matrix(, nrow = (length(unique(data_ind))-1), ncol = 3)
  info=matrix(, nrow = (length(unique(data_ind))-1), ncol = 2)
  iter=0
for (i in unique(data_ind)){
  if (i=="NA18498"){
    next}
  iter=iter+1
  x=full_data[ , grepl(i, names(full_data))]
  x=t(data.matrix(x))
  est[iter,]=MaximumLikelihood(x)
  info[iter,1]=i
  info[iter,2]=dim(x)[1]}
return(list(est,info))}
```


```{r}
top_gene<-clean_data[1,]
x=estimate_MLE_one_gene(top_gene)
estimates=x[[1]]
info=x[[2]]
```


```{r}
par(mfrow=c(1,3))
na18507=top_gene[ , grepl("NA18507", names(top_gene))]
hist(data.matrix(na18507), xlab="Number of molecules", main="Distribution of protein expression") #Real data


lines(281*dBP(matrix(seq(0,110,by=1)),estimates[20,1],estimates[20,2],estimates[20,3]))


beta=dbeta(seq(0,1,by=0.001),estimates[20,1],estimates[20,2])
plot(beta, main="Beta distribution with estimated parameters", type="l")

beta=rbeta(1000,estimates[20,1],estimates[20,2])
poisson=rpois(1000,beta*estimates[20,3])
hist(poisson, xlab="Number of molecules",main="Poisson distribution")
```



